# Generated by Django 5.1 on 2024-09-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='repeat',
            field=models.CharField(choices=[('NONE', 'No Repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
