# Generated by Django 5.1 on 2024-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0002_calendarevent_repeat_calendarevent_repeat_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='custom_repeat_interval',
            field=models.PositiveIntegerField(blank=True, help_text='Interval for custom recurrence in days.', null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='custom_repeat_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='repeat',
            field=models.CharField(choices=[('NONE', 'No Repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='NONE', max_length=10),
        ),
    ]
